### PR TITLE
add 'disabled' classNameBinding and attributeBinding to list item

### PR DESCRIPTION
**Pull request by jamesstaub**
Allows usage of MDC disabled list item style

### CODE REVIEW

**Comment by hilljh82** [comment]
@jamesstaub Thank you for the full request. I am curious why you are adding `disabled` to `attributeBindings`, and not just to `classNameBindings`? It seems the correct solution is to update the `classNameBindings` with support for disabled list items? `attributeBindings` are for adding HTML attributes to the component tag. Let me know if I am missing something.

**Comment by jamesstaub** [comment]
You're correct, I was misunderstanding how the bindings worked. Please see latest commit.

**Comment by hilljh82** [comment]
@jamesstaub Thanks for making the corrections. I will go ahead and merge the pull-request. I am going to assume this is a feature you need right now. If so, I can go ahead and make a quick release.

**Comment by jamesstaub** [comment]
it is indeed, thank you!

**Comment by hilljh82** [comment]
Done!

**Pull request merged**
